all: false
dir: '{{.InterfaceDir}}'
filename: mocks.gen.go
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/muriiloandrade/finsplitter/internal/domain:
    config:
      all: true
  github.com/muriiloandrade/finsplitter/internal/app/ports:
    config:
      all: true
  github.com/muriiloandrade/finsplitter/internal/app/usecases/card-brand:
    config:
      all: true
  github.com/muriiloandrade/finsplitter/internal/app/usecases/auth:
    config:
      all: false
    interfaces:
      LogtoDeviceFlowClient:
      LogtoUserCreator:
  github.com/muriiloandrade/finsplitter/internal/gateways/http/v1/auth:
    config:
      all: false
    interfaces:
      jwkFetcher:
      deviceAuthUseCase:
      devicePollUseCase:
