codecov:
    branch: main
    notify:
        wait_for_ci: false

comment:
    layout: "diff, flags, files"
    behavior: default
    require_changes: true
    require_base: false
    require_head: true
    hide_project_coverage: false

github_checks:
    annotations: false

flags:
    unit:
        paths:
            - "**/*.go"
            - "!**/testutils/**"
            - "!**/*mocks.gen.go"
    testutils:
        paths:
            - "**/testutils/**"

coverage:
    range: 50..80
    round: down
    precision: 1
    status:
        project:
            default:
                informational: true
                flags:
                    - unit
        patch:
            default:
                informational: true

ignore:
    - "**/*mocks.gen.go"
    - "**/testutils/**"
