services:
    otel:
        profiles:
            - monitoring
        container_name: finsplitter-lgtm
        image: grafana/otel-lgtm:0.23.0@sha256:dde2dcd51e955e27e1ab454e6ba8e6f8c958e7d22dca1d4ab0be87fa64198051
        networks:
            - finsplitter
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "3000:3000"
            - "4317:4317"
            - "4318:4318"
            - "9090:9090"
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_SECURITY_ALLOW_EMBEDDING=true
