---
include:
    - compose.infra.yml
    - compose.debug.yml
    - compose.monitoring.yml

services:
    api:
        image: finsplitter:dev
        container_name: finsplitter
        profiles:
            - backend
        build:
            context: .
            dockerfile: ./Dockerfile
            target: setup
        env_file:
            - .env
        environment:
            - GOEXPERIMENT=jsonv2
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT}:${APP_PORT}"
        command: go run cmd/api/main.go
        develop:
            watch:
                - path: ./
                  target: /app
                  action: sync+restart
                - path: go.mod
                  action: rebuild
                - path: go.sum
                  action: rebuild
        depends_on:
            postgresql:
                condition: service_healthy
        networks:
            - finsplitter
    logto:
        profiles:
            - infra
        container_name: logto
        depends_on:
            postgresql:
                condition: service_healthy
        image: svhd/logto:${TAG-latest}
        entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
        ports:
            - "${LOGTO_PORT:-3001}:3001"
            - "${LOGTO_PORT_MGMT:-3002}:3002"
        environment:
            - TRUST_PROXY_HEADER=1
            - DB_URL=${LOGTO_DB_URL}
            - ENDPOINT=${LOGTO_ENDPOINT}
            - ADMIN_ENDPOINT=${LOGTO_ADMIN_ENDPOINT}
        env_file:
            - .env
        networks:
            - finsplitter

networks:
    finsplitter:
        name: finsplitter-net
        external: true
