---
include:
    - compose.infra.yml
    - compose.debug.yml
    - compose.monitoring.yml

services:
    api:
        image: finsplitter:dev
        container_name: finsplitter
        profiles:
            - backend
        build:
            context: .
            dockerfile: ./Dockerfile
            target: setup
        env_file:
            - .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT}:${APP_PORT}"
        command: go run cmd/api/main.go
        develop:
            watch:
                - path: ./
                  target: /app
                  action: sync+restart
                - path: go.mod
                  action: rebuild
                - path: go.sum
                  action: rebuild
        depends_on:
            postgresql:
                condition: service_healthy
        networks:
            - finsplitter
    logto:
        container_name: logto
        depends_on:
            postgresql:
                condition: service_healthy
        image: svhd/logto:${TAG-latest}
        entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
        ports:
            - 3001:3001
            - 3002:3002
        environment:
            - TRUST_PROXY_HEADER=1
            - DB_URL=${LOGTO_PG_URL}
            # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
            # Or, you can leverage it for local testing.
            - ENDPOINT
            - ADMIN_ENDPOINT

networks:
    finsplitter:
        name: finsplitter-net
        external: true
