---
services:
    postgresql:
        profiles:
            - infra
        image: postgres:18.6-trixie@sha256:06cad38a5d9f5d24b4d83d86def30795d5e4b757fedbf5281172b576dedcd941
        container_name: finsplitter-db
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}",
                ]
            start_period: 20s
            interval: 30s
            retries: 5
            timeout: 5s
        volumes:
            - database:/var/lib/postgresql
        ports:
            - ${PG_PORT:-5432}:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASS:?database password required}
            POSTGRES_USER: ${PG_USER:-finsplitter}
            POSTGRES_DB: ${PG_DB:-finsplitter}
        env_file:
            - .env
        networks:
            - finsplitter

    valkey:
        profiles:
            - infra
        image: valkey/valkey:9.1.2-trixie@sha256:a91d34ab33975b1054e26f1bd9995b268f7e0c507b5ded7f3d181a1a25521630
        container_name: finsplitter-valkey
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "valkey-cli", "ping"]
            start_period: 5s
            interval: 10s
            retries: 5
            timeout: 3s
        ports:
            - "${VALKEY_PORT:-6379}:6379"
        networks:
            - finsplitter
        volumes:
            - valkey-data:/data

volumes:
    database:
        driver: local
    valkey-data:
        driver: local
