---
services:
    postgresql:
        profiles:
            - infra
        image: postgres:18.3-trixie@sha256:69e8582b781cb44fa4557b98ed586fe68361e320d9b12f9707494335634f4f3d
        container_name: finsplitter-db
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}",
                ]
            start_period: 20s
            interval: 30s
            retries: 5
            timeout: 5s
        volumes:
            - database:/var/lib/postgresql
        ports:
            - ${PG_PORT:-5432}:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASS:?database password required}
            POSTGRES_USER: ${PG_USER:-finsplitter}
            POSTGRES_DB: ${PG_DB:-finsplitter}
        env_file:
            - .env
        networks:
            - finsplitter

volumes:
    database:
        driver: local
