---
services:
    postgresql:
        profiles:
            - infra
        image: postgres:18.2-trixie@sha256:b6b4d0b75c699a2c94dfc5a94fe09f38630f3b67ab0e1653ede1b7ac8e13c197
        container_name: finsplitter-db
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}",
                ]
            start_period: 20s
            interval: 30s
            retries: 5
            timeout: 5s
        volumes:
            - database:/var/lib/postgresql
        ports:
            - ${PG_PORT:-5432}:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASS:?database password required}
            POSTGRES_USER: ${PG_USER:-finsplitter}
            POSTGRES_DB: ${PG_DB:-finsplitter}
        env_file:
            - .env
        networks:
            - finsplitter

volumes:
    database:
        driver: local
