services:
    otel:
        profiles:
            - monitoring
        container_name: finsplitter-lgtm
        image: grafana/otel-lgtm:0.31.0@sha256:f1e548c20c99d2678744be9d90955c0ab208ecc273db2a7a0b5dc5673d0b57fd
        networks:
            - finsplitter
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "3000:3000"
            - "4317:4317"
            - "4318:4318"
            - "9090:9090"
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_SECURITY_ALLOW_EMBEDDING=true
