// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecases

import (
	"context"

	"github.com/gofrs/uuid/v5"
	"github.com/muriiloandrade/finsplitter/internal/app/ports"
	"github.com/muriiloandrade/finsplitter/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateCardBrandUseCase creates a new instance of MockCreateCardBrandUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCardBrandUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCardBrandUseCase {
	mock := &MockCreateCardBrandUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateCardBrandUseCase is an autogenerated mock type for the CreateCardBrandUseCase type
type MockCreateCardBrandUseCase struct {
	mock.Mock
}

type MockCreateCardBrandUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateCardBrandUseCase) EXPECT() *MockCreateCardBrandUseCase_Expecter {
	return &MockCreateCardBrandUseCase_Expecter{mock: &_m.Mock}
}

// CreateCardBrand provides a mock function for the type MockCreateCardBrandUseCase
func (_mock *MockCreateCardBrandUseCase) CreateCardBrand(ctx context.Context, name string) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateCardBrandUseCase_CreateCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCardBrand'
type MockCreateCardBrandUseCase_CreateCardBrand_Call struct {
	*mock.Call
}

// CreateCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCreateCardBrandUseCase_Expecter) CreateCardBrand(ctx any, name any) *MockCreateCardBrandUseCase_CreateCardBrand_Call {
	return &MockCreateCardBrandUseCase_CreateCardBrand_Call{Call: _e.mock.On("CreateCardBrand", ctx, name)}
}

func (_c *MockCreateCardBrandUseCase_CreateCardBrand_Call) Run(run func(ctx context.Context, name string)) *MockCreateCardBrandUseCase_CreateCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateCardBrandUseCase_CreateCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockCreateCardBrandUseCase_CreateCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockCreateCardBrandUseCase_CreateCardBrand_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.CardBrand, error)) *MockCreateCardBrandUseCase_CreateCardBrand_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCardBrandByIDUseCase creates a new instance of MockGetCardBrandByIDUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCardBrandByIDUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCardBrandByIDUseCase {
	mock := &MockGetCardBrandByIDUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetCardBrandByIDUseCase is an autogenerated mock type for the GetCardBrandByIDUseCase type
type MockGetCardBrandByIDUseCase struct {
	mock.Mock
}

type MockGetCardBrandByIDUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCardBrandByIDUseCase) EXPECT() *MockGetCardBrandByIDUseCase_Expecter {
	return &MockGetCardBrandByIDUseCase_Expecter{mock: &_m.Mock}
}

// GetCardBrandByID provides a mock function for the type MockGetCardBrandByIDUseCase
func (_mock *MockGetCardBrandByIDUseCase) GetCardBrandByID(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCardBrandByID")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetCardBrandByIDUseCase_GetCardBrandByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardBrandByID'
type MockGetCardBrandByIDUseCase_GetCardBrandByID_Call struct {
	*mock.Call
}

// GetCardBrandByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGetCardBrandByIDUseCase_Expecter) GetCardBrandByID(ctx any, id any) *MockGetCardBrandByIDUseCase_GetCardBrandByID_Call {
	return &MockGetCardBrandByIDUseCase_GetCardBrandByID_Call{Call: _e.mock.On("GetCardBrandByID", ctx, id)}
}

func (_c *MockGetCardBrandByIDUseCase_GetCardBrandByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGetCardBrandByIDUseCase_GetCardBrandByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetCardBrandByIDUseCase_GetCardBrandByID_Call) Return(cardBrand *entity.CardBrand, err error) *MockGetCardBrandByIDUseCase_GetCardBrandByID_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockGetCardBrandByIDUseCase_GetCardBrandByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error)) *MockGetCardBrandByIDUseCase_GetCardBrandByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListCardBrandsUseCase creates a new instance of MockListCardBrandsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListCardBrandsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListCardBrandsUseCase {
	mock := &MockListCardBrandsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListCardBrandsUseCase is an autogenerated mock type for the ListCardBrandsUseCase type
type MockListCardBrandsUseCase struct {
	mock.Mock
}

type MockListCardBrandsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListCardBrandsUseCase) EXPECT() *MockListCardBrandsUseCase_Expecter {
	return &MockListCardBrandsUseCase_Expecter{mock: &_m.Mock}
}

// ListCardBrands provides a mock function for the type MockListCardBrandsUseCase
func (_mock *MockListCardBrandsUseCase) ListCardBrands(ctx context.Context, opts ports.ListCardBrandFilterOptions) ([]entity.CardBrand, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListCardBrands")
	}

	var r0 []entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ListCardBrandFilterOptions) ([]entity.CardBrand, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ListCardBrandFilterOptions) []entity.CardBrand); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.ListCardBrandFilterOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListCardBrandsUseCase_ListCardBrands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCardBrands'
type MockListCardBrandsUseCase_ListCardBrands_Call struct {
	*mock.Call
}

// ListCardBrands is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ports.ListCardBrandFilterOptions
func (_e *MockListCardBrandsUseCase_Expecter) ListCardBrands(ctx any, opts any) *MockListCardBrandsUseCase_ListCardBrands_Call {
	return &MockListCardBrandsUseCase_ListCardBrands_Call{Call: _e.mock.On("ListCardBrands", ctx, opts)}
}

func (_c *MockListCardBrandsUseCase_ListCardBrands_Call) Run(run func(ctx context.Context, opts ports.ListCardBrandFilterOptions)) *MockListCardBrandsUseCase_ListCardBrands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.ListCardBrandFilterOptions
		if args[1] != nil {
			arg1 = args[1].(ports.ListCardBrandFilterOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListCardBrandsUseCase_ListCardBrands_Call) Return(cardBrands []entity.CardBrand, err error) *MockListCardBrandsUseCase_ListCardBrands_Call {
	_c.Call.Return(cardBrands, err)
	return _c
}

func (_c *MockListCardBrandsUseCase_ListCardBrands_Call) RunAndReturn(run func(ctx context.Context, opts ports.ListCardBrandFilterOptions) ([]entity.CardBrand, error)) *MockListCardBrandsUseCase_ListCardBrands_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateCardBrandUseCase creates a new instance of MockUpdateCardBrandUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateCardBrandUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateCardBrandUseCase {
	mock := &MockUpdateCardBrandUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateCardBrandUseCase is an autogenerated mock type for the UpdateCardBrandUseCase type
type MockUpdateCardBrandUseCase struct {
	mock.Mock
}

type MockUpdateCardBrandUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateCardBrandUseCase) EXPECT() *MockUpdateCardBrandUseCase_Expecter {
	return &MockUpdateCardBrandUseCase_Expecter{mock: &_m.Mock}
}

// UpdateCardBrand provides a mock function for the type MockUpdateCardBrandUseCase
func (_mock *MockUpdateCardBrandUseCase) UpdateCardBrand(ctx context.Context, opts ports.UpdateCardBrandOptions) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.UpdateCardBrandOptions) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.UpdateCardBrandOptions) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.UpdateCardBrandOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateCardBrandUseCase_UpdateCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCardBrand'
type MockUpdateCardBrandUseCase_UpdateCardBrand_Call struct {
	*mock.Call
}

// UpdateCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ports.UpdateCardBrandOptions
func (_e *MockUpdateCardBrandUseCase_Expecter) UpdateCardBrand(ctx any, opts any) *MockUpdateCardBrandUseCase_UpdateCardBrand_Call {
	return &MockUpdateCardBrandUseCase_UpdateCardBrand_Call{Call: _e.mock.On("UpdateCardBrand", ctx, opts)}
}

func (_c *MockUpdateCardBrandUseCase_UpdateCardBrand_Call) Run(run func(ctx context.Context, opts ports.UpdateCardBrandOptions)) *MockUpdateCardBrandUseCase_UpdateCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.UpdateCardBrandOptions
		if args[1] != nil {
			arg1 = args[1].(ports.UpdateCardBrandOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateCardBrandUseCase_UpdateCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockUpdateCardBrandUseCase_UpdateCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockUpdateCardBrandUseCase_UpdateCardBrand_Call) RunAndReturn(run func(ctx context.Context, opts ports.UpdateCardBrandOptions) (*entity.CardBrand, error)) *MockUpdateCardBrandUseCase_UpdateCardBrand_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteCardBrandUseCase creates a new instance of MockDeleteCardBrandUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteCardBrandUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteCardBrandUseCase {
	mock := &MockDeleteCardBrandUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleteCardBrandUseCase is an autogenerated mock type for the DeleteCardBrandUseCase type
type MockDeleteCardBrandUseCase struct {
	mock.Mock
}

type MockDeleteCardBrandUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteCardBrandUseCase) EXPECT() *MockDeleteCardBrandUseCase_Expecter {
	return &MockDeleteCardBrandUseCase_Expecter{mock: &_m.Mock}
}

// DeleteCardBrand provides a mock function for the type MockDeleteCardBrandUseCase
func (_mock *MockDeleteCardBrandUseCase) DeleteCardBrand(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeleteCardBrandUseCase_DeleteCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCardBrand'
type MockDeleteCardBrandUseCase_DeleteCardBrand_Call struct {
	*mock.Call
}

// DeleteCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeleteCardBrandUseCase_Expecter) DeleteCardBrand(ctx any, id any) *MockDeleteCardBrandUseCase_DeleteCardBrand_Call {
	return &MockDeleteCardBrandUseCase_DeleteCardBrand_Call{Call: _e.mock.On("DeleteCardBrand", ctx, id)}
}

func (_c *MockDeleteCardBrandUseCase_DeleteCardBrand_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeleteCardBrandUseCase_DeleteCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleteCardBrandUseCase_DeleteCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockDeleteCardBrandUseCase_DeleteCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockDeleteCardBrandUseCase_DeleteCardBrand_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error)) *MockDeleteCardBrandUseCase_DeleteCardBrand_Call {
	_c.Call.Return(run)
	return _c
}
