// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package profile

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogtoUserUpdater creates a new instance of MockLogtoUserUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogtoUserUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogtoUserUpdater {
	mock := &MockLogtoUserUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogtoUserUpdater is an autogenerated mock type for the LogtoUserUpdater type
type MockLogtoUserUpdater struct {
	mock.Mock
}

type MockLogtoUserUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogtoUserUpdater) EXPECT() *MockLogtoUserUpdater_Expecter {
	return &MockLogtoUserUpdater_Expecter{mock: &_m.Mock}
}

// UpdateUser provides a mock function for the type MockLogtoUserUpdater
func (_mock *MockLogtoUserUpdater) UpdateUser(ctx context.Context, userID string, username string, name string, phone string, picture string) error {
	ret := _mock.Called(ctx, userID, username, name, phone, picture)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, username, name, phone, picture)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLogtoUserUpdater_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockLogtoUserUpdater_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - username string
//   - name string
//   - phone string
//   - picture string
func (_e *MockLogtoUserUpdater_Expecter) UpdateUser(ctx any, userID any, username any, name any, phone any, picture any) *MockLogtoUserUpdater_UpdateUser_Call {
	return &MockLogtoUserUpdater_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, userID, username, name, phone, picture)}
}

func (_c *MockLogtoUserUpdater_UpdateUser_Call) Run(run func(ctx context.Context, userID string, username string, name string, phone string, picture string)) *MockLogtoUserUpdater_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockLogtoUserUpdater_UpdateUser_Call) Return(err error) *MockLogtoUserUpdater_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLogtoUserUpdater_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, userID string, username string, name string, phone string, picture string) error) *MockLogtoUserUpdater_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
