// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/lestrrat-go/jwx/v4/jwk"
	"github.com/muriiloandrade/finsplitter/internal/app/usecases/auth"
	mock "github.com/stretchr/testify/mock"
)

// newMockdeviceAuthUseCase creates a new instance of mockdeviceAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdeviceAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdeviceAuthUseCase {
	mock := &mockdeviceAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdeviceAuthUseCase is an autogenerated mock type for the deviceAuthUseCase type
type mockdeviceAuthUseCase struct {
	mock.Mock
}

type mockdeviceAuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdeviceAuthUseCase) EXPECT() *mockdeviceAuthUseCase_Expecter {
	return &mockdeviceAuthUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type mockdeviceAuthUseCase
func (_mock *mockdeviceAuthUseCase) Execute(ctx context.Context, input auth.RequestDeviceAuthInput) (*auth.RequestDeviceAuthOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *auth.RequestDeviceAuthOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RequestDeviceAuthInput) (*auth.RequestDeviceAuthOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RequestDeviceAuthInput) *auth.RequestDeviceAuthOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RequestDeviceAuthOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.RequestDeviceAuthInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdeviceAuthUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockdeviceAuthUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input auth.RequestDeviceAuthInput
func (_e *mockdeviceAuthUseCase_Expecter) Execute(ctx any, input any) *mockdeviceAuthUseCase_Execute_Call {
	return &mockdeviceAuthUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *mockdeviceAuthUseCase_Execute_Call) Run(run func(ctx context.Context, input auth.RequestDeviceAuthInput)) *mockdeviceAuthUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RequestDeviceAuthInput
		if args[1] != nil {
			arg1 = args[1].(auth.RequestDeviceAuthInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdeviceAuthUseCase_Execute_Call) Return(requestDeviceAuthOutput *auth.RequestDeviceAuthOutput, err error) *mockdeviceAuthUseCase_Execute_Call {
	_c.Call.Return(requestDeviceAuthOutput, err)
	return _c
}

func (_c *mockdeviceAuthUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, input auth.RequestDeviceAuthInput) (*auth.RequestDeviceAuthOutput, error)) *mockdeviceAuthUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdevicePollUseCase creates a new instance of mockdevicePollUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdevicePollUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdevicePollUseCase {
	mock := &mockdevicePollUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdevicePollUseCase is an autogenerated mock type for the devicePollUseCase type
type mockdevicePollUseCase struct {
	mock.Mock
}

type mockdevicePollUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdevicePollUseCase) EXPECT() *mockdevicePollUseCase_Expecter {
	return &mockdevicePollUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type mockdevicePollUseCase
func (_mock *mockdevicePollUseCase) Execute(ctx context.Context, input auth.PollDeviceTokenInput) (*auth.PollDeviceTokenOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *auth.PollDeviceTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.PollDeviceTokenInput) (*auth.PollDeviceTokenOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.PollDeviceTokenInput) *auth.PollDeviceTokenOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.PollDeviceTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.PollDeviceTokenInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdevicePollUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockdevicePollUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input auth.PollDeviceTokenInput
func (_e *mockdevicePollUseCase_Expecter) Execute(ctx any, input any) *mockdevicePollUseCase_Execute_Call {
	return &mockdevicePollUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *mockdevicePollUseCase_Execute_Call) Run(run func(ctx context.Context, input auth.PollDeviceTokenInput)) *mockdevicePollUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.PollDeviceTokenInput
		if args[1] != nil {
			arg1 = args[1].(auth.PollDeviceTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdevicePollUseCase_Execute_Call) Return(pollDeviceTokenOutput *auth.PollDeviceTokenOutput, err error) *mockdevicePollUseCase_Execute_Call {
	_c.Call.Return(pollDeviceTokenOutput, err)
	return _c
}

func (_c *mockdevicePollUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, input auth.PollDeviceTokenInput) (*auth.PollDeviceTokenOutput, error)) *mockdevicePollUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdeviceRefreshUseCase creates a new instance of mockdeviceRefreshUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdeviceRefreshUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdeviceRefreshUseCase {
	mock := &mockdeviceRefreshUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdeviceRefreshUseCase is an autogenerated mock type for the deviceRefreshUseCase type
type mockdeviceRefreshUseCase struct {
	mock.Mock
}

type mockdeviceRefreshUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdeviceRefreshUseCase) EXPECT() *mockdeviceRefreshUseCase_Expecter {
	return &mockdeviceRefreshUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type mockdeviceRefreshUseCase
func (_mock *mockdeviceRefreshUseCase) Execute(ctx context.Context, input auth.RefreshDeviceTokenInput) (*auth.RefreshDeviceTokenOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *auth.RefreshDeviceTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RefreshDeviceTokenInput) (*auth.RefreshDeviceTokenOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RefreshDeviceTokenInput) *auth.RefreshDeviceTokenOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshDeviceTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.RefreshDeviceTokenInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdeviceRefreshUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockdeviceRefreshUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input auth.RefreshDeviceTokenInput
func (_e *mockdeviceRefreshUseCase_Expecter) Execute(ctx any, input any) *mockdeviceRefreshUseCase_Execute_Call {
	return &mockdeviceRefreshUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *mockdeviceRefreshUseCase_Execute_Call) Run(run func(ctx context.Context, input auth.RefreshDeviceTokenInput)) *mockdeviceRefreshUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RefreshDeviceTokenInput
		if args[1] != nil {
			arg1 = args[1].(auth.RefreshDeviceTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdeviceRefreshUseCase_Execute_Call) Return(refreshDeviceTokenOutput *auth.RefreshDeviceTokenOutput, err error) *mockdeviceRefreshUseCase_Execute_Call {
	_c.Call.Return(refreshDeviceTokenOutput, err)
	return _c
}

func (_c *mockdeviceRefreshUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, input auth.RefreshDeviceTokenInput) (*auth.RefreshDeviceTokenOutput, error)) *mockdeviceRefreshUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockjwkFetcher creates a new instance of mockjwkFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjwkFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjwkFetcher {
	mock := &mockjwkFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjwkFetcher is an autogenerated mock type for the jwkFetcher type
type mockjwkFetcher struct {
	mock.Mock
}

type mockjwkFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjwkFetcher) EXPECT() *mockjwkFetcher_Expecter {
	return &mockjwkFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type mockjwkFetcher
func (_mock *mockjwkFetcher) Fetch(ctx context.Context, url string) (jwk.Set, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 jwk.Set
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (jwk.Set, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) jwk.Set); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwk.Set)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjwkFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type mockjwkFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *mockjwkFetcher_Expecter) Fetch(ctx any, url any) *mockjwkFetcher_Fetch_Call {
	return &mockjwkFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx, url)}
}

func (_c *mockjwkFetcher_Fetch_Call) Run(run func(ctx context.Context, url string)) *mockjwkFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockjwkFetcher_Fetch_Call) Return(set jwk.Set, err error) *mockjwkFetcher_Fetch_Call {
	_c.Call.Return(set, err)
	return _c
}

func (_c *mockjwkFetcher_Fetch_Call) RunAndReturn(run func(ctx context.Context, url string) (jwk.Set, error)) *mockjwkFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
