// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/lestrrat-go/jwx/v4/jwk"
	mock "github.com/stretchr/testify/mock"
)

// newMockjwkFetcher creates a new instance of mockjwkFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjwkFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjwkFetcher {
	mock := &mockjwkFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjwkFetcher is an autogenerated mock type for the jwkFetcher type
type mockjwkFetcher struct {
	mock.Mock
}

type mockjwkFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjwkFetcher) EXPECT() *mockjwkFetcher_Expecter {
	return &mockjwkFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type mockjwkFetcher
func (_mock *mockjwkFetcher) Fetch(ctx context.Context, url string) (jwk.Set, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 jwk.Set
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (jwk.Set, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) jwk.Set); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwk.Set)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjwkFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type mockjwkFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *mockjwkFetcher_Expecter) Fetch(ctx any, url any) *mockjwkFetcher_Fetch_Call {
	return &mockjwkFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx, url)}
}

func (_c *mockjwkFetcher_Fetch_Call) Run(run func(ctx context.Context, url string)) *mockjwkFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockjwkFetcher_Fetch_Call) Return(set jwk.Set, err error) *mockjwkFetcher_Fetch_Call {
	_c.Call.Return(set, err)
	return _c
}

func (_c *mockjwkFetcher_Fetch_Call) RunAndReturn(run func(ctx context.Context, url string) (jwk.Set, error)) *mockjwkFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
