// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card_brand.sql

package sqlc

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
)

const CreateCardBrand = `-- name: CreateCardBrand :one
INSERT INTO card_brand (
  name
) VALUES (
  $1
)
RETURNING id, name, created_date, last_modified_date
`

type CreateCardBrandParams struct {
	Name string `db:"name" json:"name"`
}

func (q *Queries) CreateCardBrand(ctx context.Context, arg CreateCardBrandParams) (CardBrand, error) {
	row := q.db.QueryRow(ctx, CreateCardBrand, arg.Name)
	var i CardBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const DeleteCardBrand = `-- name: DeleteCardBrand :one
DELETE FROM card_brand
WHERE id = $1
RETURNING id, name, created_date, last_modified_date
`

type DeleteCardBrandParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteCardBrand(ctx context.Context, arg DeleteCardBrandParams) (CardBrand, error) {
	row := q.db.QueryRow(ctx, DeleteCardBrand, arg.ID)
	var i CardBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const GetCardBrand = `-- name: GetCardBrand :one
SELECT id, name, created_date, last_modified_date FROM card_brand
WHERE id = $1 LIMIT 1
`

type GetCardBrandParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCardBrand(ctx context.Context, arg GetCardBrandParams) (CardBrand, error) {
	row := q.db.QueryRow(ctx, GetCardBrand, arg.ID)
	var i CardBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const ListCardBrands = `-- name: ListCardBrands :many
SELECT id, name, created_date, last_modified_date
FROM card_brand cb
WHERE
  ($1::text IS NULL OR cb.id = $1::uuid)
  AND
  ($2::text IS NULL OR $2::text = '' OR cb.name ILIKE '%' || $2::text || '%')
ORDER BY name
LIMIT $4::bigint OFFSET $3::bigint
`

type ListCardBrandsParams struct {
	ID         *string `db:"id" json:"id"`
	Name       *string `db:"name" json:"name"`
	PageOffset int64   `db:"page_offset" json:"pageOffset"`
	PageSize   int64   `db:"page_size" json:"pageSize"`
}

func (q *Queries) ListCardBrands(ctx context.Context, arg ListCardBrandsParams) ([]CardBrand, error) {
	rows, err := q.db.Query(ctx, ListCardBrands,
		arg.ID,
		arg.Name,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardBrand
	for rows.Next() {
		var i CardBrand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedDate,
			&i.LastModifiedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCardBrand = `-- name: UpdateCardBrand :one
UPDATE card_brand
SET name = $1
WHERE id = $2
RETURNING id, name, created_date, last_modified_date
`

type UpdateCardBrandParams struct {
	Name string    `db:"name" json:"name"`
	ID   uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateCardBrand(ctx context.Context, arg UpdateCardBrandParams) (CardBrand, error) {
	row := q.db.QueryRow(ctx, UpdateCardBrand, arg.Name, arg.ID)
	var i CardBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}
