// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: card_brand.sql

package sqlc

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
)

const CreateCardBrand = `-- name: CreateCardBrand :one
INSERT INTO card_brand (
  name
) VALUES (
  $1
)
RETURNING id, name, created_date, last_modified_date
`

type CreateCardBrandParams struct {
	Name string `db:"name" json:"name"`
}

func (q *Queries) CreateCardBrand(ctx context.Context, arg CreateCardBrandParams) (CardBrand, error) {
	row := q.db.QueryRow(ctx, CreateCardBrand, arg.Name)
	var i CardBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const DeleteCardBrand = `-- name: DeleteCardBrand :exec
DELETE FROM card_brand
WHERE id = $1
`

type DeleteCardBrandParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteCardBrand(ctx context.Context, arg DeleteCardBrandParams) error {
	_, err := q.db.Exec(ctx, DeleteCardBrand, arg.ID)
	return err
}

const GetCardBrand = `-- name: GetCardBrand :one
SELECT id, name, created_date, last_modified_date FROM card_brand
WHERE id = $1 LIMIT 1
`

type GetCardBrandParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCardBrand(ctx context.Context, arg GetCardBrandParams) (CardBrand, error) {
	row := q.db.QueryRow(ctx, GetCardBrand, arg.ID)
	var i CardBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const ListCardBrands = `-- name: ListCardBrands :many
SELECT id, name, created_date, last_modified_date FROM card_brand
ORDER BY name
`

func (q *Queries) ListCardBrands(ctx context.Context) ([]CardBrand, error) {
	rows, err := q.db.Query(ctx, ListCardBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardBrand
	for rows.Next() {
		var i CardBrand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedDate,
			&i.LastModifiedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
