// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Bill struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	CardID           uuid.UUID          `db:"card_id" json:"cardId"`
	Month            int16              `db:"month" json:"month"`
	Year             int16              `db:"year" json:"year"`
	DueDate          int16              `db:"due_date" json:"dueDate"`
	DueMonth         int16              `db:"due_month" json:"dueMonth"`
	Paid             *bool              `db:"paid" json:"paid"`
	PaidOn           pgtype.Date        `db:"paid_on" json:"paidOn"`
	CreatedDate      pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}

type Card struct {
	ID      uuid.UUID `db:"id" json:"id"`
	BrandID uuid.UUID `db:"brand_id" json:"brandId"`
	UserID  uuid.UUID `db:"user_id" json:"userId"`
	Name    string    `db:"name" json:"name"`
	// Last 4 digits, corresponde aos 4 últimos dígitos do número docartão
	L4d *string `db:"l4d" json:"l4d"`
	// O dia do mês que a fatura vence
	DueDate int16 `db:"due_date" json:"dueDate"`
	// O dia do mês que a fatura fecha
	ClosingDate *int16 `db:"closing_date" json:"closingDate"`
	// Exemplos: Black, Platinum, entre outros
	Tier             *string            `db:"tier" json:"tier"`
	CreatedDate      pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}

type CardBrand struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	CreatedDate      pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}

type CardPerson struct {
	CardID            uuid.UUID          `db:"card_id" json:"cardId"`
	PersonID          uuid.UUID          `db:"person_id" json:"personId"`
	DefaultPercentage *decimal.Decimal   `db:"default_percentage" json:"defaultPercentage"`
	CreatedDate       pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	EndDate           pgtype.Timestamptz `db:"end_date" json:"endDate"`
}

type Person struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	UserID           uuid.UUID          `db:"user_id" json:"userId"`
	Name             string             `db:"name" json:"name"`
	CreatedDate      pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}

type Transaction struct {
	ID     uuid.UUID `db:"id" json:"id"`
	CardID uuid.UUID `db:"card_id" json:"cardId"`
	BillID uuid.UUID `db:"bill_id" json:"billId"`
	// Identificador da transação - como consta na fatura do banco
	Identifier *string `db:"identifier" json:"identifier"`
	// Como quer identificar essa transação
	Name  *string          `db:"name" json:"name"`
	Value *decimal.Decimal `db:"value" json:"value"`
	Date  pgtype.Date      `db:"date" json:"date"`
	// Indica se a transação estará presente em mais de 1 fatura
	RecurringCharge    bool               `db:"recurring_charge" json:"recurringCharge"`
	InstallmentsNumber *int16             `db:"installments_number" json:"installmentsNumber"`
	CreatedDate        pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate   pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}

type TransactionPerson struct {
	PersonID        uuid.UUID          `db:"person_id" json:"personId"`
	TransactionID   uuid.UUID          `db:"transaction_id" json:"transactionId"`
	Percentage      *decimal.Decimal   `db:"percentage" json:"percentage"`
	CalculatedValue *decimal.Decimal   `db:"calculated_value" json:"calculatedValue"`
	CreatedDate     pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	EndDate         pgtype.Timestamptz `db:"end_date" json:"endDate"`
}

type User struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Email            string             `db:"email" json:"email"`
	PhoneNumber      *string            `db:"phone_number" json:"phoneNumber"`
	Username         string             `db:"username" json:"username"`
	PasswordHash     string             `db:"password_hash" json:"passwordHash"`
	CreatedDate      pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}
