// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package sqlc

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO "user" (name, email, phone_number, username, password_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone_number, username, password_hash, created_date, last_modified_date
`

type CreateUserParams struct {
	Name         string  `db:"name" json:"name"`
	Email        string  `db:"email" json:"email"`
	PhoneNumber  *string `db:"phone_number" json:"phoneNumber"`
	Username     string  `db:"username" json:"username"`
	PasswordHash string  `db:"password_hash" json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.Username,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM "user" WHERE id = $1
`

type DeleteUserParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, DeleteUser, arg.ID)
	return err
}

const GetUser = `-- name: GetUser :one
SELECT id, name, email, phone_number, username, password_hash, created_date, last_modified_date
FROM "user"
WHERE id = $1
`

type GetUserParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, GetUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, name, email, phone_number, username, password_hash, created_date, last_modified_date
FROM "user"
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedDate,
			&i.LastModifiedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE "user"
SET name = $1, email = $2, phone_number = $3, username = $4, password_hash = $5
WHERE id = $6
RETURNING id, name, email, phone_number, username, password_hash, created_date, last_modified_date
`

type UpdateUserParams struct {
	Name         string    `db:"name" json:"name"`
	Email        string    `db:"email" json:"email"`
	PhoneNumber  *string   `db:"phone_number" json:"phoneNumber"`
	Username     string    `db:"username" json:"username"`
	PasswordHash string    `db:"password_hash" json:"passwordHash"`
	ID           uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, UpdateUser,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.Username,
		arg.PasswordHash,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}
