// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO "user" (
    logto_user_id, username, email, created_date, last_modified_date
) VALUES (
    $1, $2, $3, NOW(), NOW()
)
RETURNING id, name, email, phone_number, username, password_hash, logto_user_id, created_date, last_modified_date
`

type CreateUserParams struct {
	LogtoUserID *string `db:"logto_user_id" json:"logtoUserId"`
	Username    string  `db:"username" json:"username"`
	Email       string  `db:"email" json:"email"`
}

type CreateUserRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Email            string             `db:"email" json:"email"`
	PhoneNumber      *string            `db:"phone_number" json:"phoneNumber"`
	Username         string             `db:"username" json:"username"`
	PasswordHash     *string            `db:"password_hash" json:"passwordHash"`
	LogtoUserID      *string            `db:"logto_user_id" json:"logtoUserId"`
	CreatedDate      pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.LogtoUserID, arg.Username, arg.Email)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.PasswordHash,
		&i.LogtoUserID,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const ExistsByLogtoUserID = `-- name: ExistsByLogtoUserID :one
SELECT EXISTS(SELECT 1 FROM "user" WHERE logto_user_id = $1)
`

type ExistsByLogtoUserIDParams struct {
	LogtoUserID *string `db:"logto_user_id" json:"logtoUserId"`
}

func (q *Queries) ExistsByLogtoUserID(ctx context.Context, arg ExistsByLogtoUserIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsByLogtoUserID, arg.LogtoUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone_number, username, password_hash, logto_user_id, created_date, last_modified_date
FROM "user"
WHERE id = $1
`

type GetUserByIDParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

type GetUserByIDRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Email            string             `db:"email" json:"email"`
	PhoneNumber      *string            `db:"phone_number" json:"phoneNumber"`
	Username         string             `db:"username" json:"username"`
	PasswordHash     *string            `db:"password_hash" json:"passwordHash"`
	LogtoUserID      *string            `db:"logto_user_id" json:"logtoUserId"`
	CreatedDate      pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, GetUserByID, arg.ID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.PasswordHash,
		&i.LogtoUserID,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const GetUserByLogtoUserID = `-- name: GetUserByLogtoUserID :one
SELECT id, name, email, phone_number, username, password_hash, logto_user_id, created_date, last_modified_date
FROM "user"
WHERE logto_user_id = $1
`

type GetUserByLogtoUserIDParams struct {
	LogtoUserID *string `db:"logto_user_id" json:"logtoUserId"`
}

type GetUserByLogtoUserIDRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Email            string             `db:"email" json:"email"`
	PhoneNumber      *string            `db:"phone_number" json:"phoneNumber"`
	Username         string             `db:"username" json:"username"`
	PasswordHash     *string            `db:"password_hash" json:"passwordHash"`
	LogtoUserID      *string            `db:"logto_user_id" json:"logtoUserId"`
	CreatedDate      pgtype.Timestamptz `db:"created_date" json:"createdDate"`
	LastModifiedDate pgtype.Timestamptz `db:"last_modified_date" json:"lastModifiedDate"`
}

func (q *Queries) GetUserByLogtoUserID(ctx context.Context, arg GetUserByLogtoUserIDParams) (GetUserByLogtoUserIDRow, error) {
	row := q.db.QueryRow(ctx, GetUserByLogtoUserID, arg.LogtoUserID)
	var i GetUserByLogtoUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.PasswordHash,
		&i.LogtoUserID,
		&i.CreatedDate,
		&i.LastModifiedDate,
	)
	return i, err
}

const UpdateUsername = `-- name: UpdateUsername :exec
UPDATE "user"
SET username = $2, last_modified_date = NOW()
WHERE id = $1
`

type UpdateUsernameParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Username string    `db:"username" json:"username"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.db.Exec(ctx, UpdateUsername, arg.ID, arg.Username)
	return err
}
