// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/muriiloandrade/finsplitter/internal/gateways/logto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogtoUserCreator creates a new instance of MockLogtoUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogtoUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogtoUserCreator {
	mock := &MockLogtoUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogtoUserCreator is an autogenerated mock type for the LogtoUserCreator type
type MockLogtoUserCreator struct {
	mock.Mock
}

type MockLogtoUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogtoUserCreator) EXPECT() *MockLogtoUserCreator_Expecter {
	return &MockLogtoUserCreator_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockLogtoUserCreator
func (_mock *MockLogtoUserCreator) CreateUser(ctx context.Context, username string, password string, name string, email string) (*logto.CreateUserResponse, error) {
	ret := _mock.Called(ctx, username, password, name, email)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *logto.CreateUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*logto.CreateUserResponse, error)); ok {
		return returnFunc(ctx, username, password, name, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *logto.CreateUserResponse); ok {
		r0 = returnFunc(ctx, username, password, name, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*logto.CreateUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, password, name, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogtoUserCreator_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockLogtoUserCreator_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - name string
//   - email string
func (_e *MockLogtoUserCreator_Expecter) CreateUser(ctx any, username any, password any, name any, email any) *MockLogtoUserCreator_CreateUser_Call {
	return &MockLogtoUserCreator_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, username, password, name, email)}
}

func (_c *MockLogtoUserCreator_CreateUser_Call) Run(run func(ctx context.Context, username string, password string, name string, email string)) *MockLogtoUserCreator_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockLogtoUserCreator_CreateUser_Call) Return(createUserResponse *logto.CreateUserResponse, err error) *MockLogtoUserCreator_CreateUser_Call {
	_c.Call.Return(createUserResponse, err)
	return _c
}

func (_c *MockLogtoUserCreator_CreateUser_Call) RunAndReturn(run func(ctx context.Context, username string, password string, name string, email string) (*logto.CreateUserResponse, error)) *MockLogtoUserCreator_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogtoDeviceFlowClient creates a new instance of MockLogtoDeviceFlowClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogtoDeviceFlowClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogtoDeviceFlowClient {
	mock := &MockLogtoDeviceFlowClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogtoDeviceFlowClient is an autogenerated mock type for the LogtoDeviceFlowClient type
type MockLogtoDeviceFlowClient struct {
	mock.Mock
}

type MockLogtoDeviceFlowClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogtoDeviceFlowClient) EXPECT() *MockLogtoDeviceFlowClient_Expecter {
	return &MockLogtoDeviceFlowClient_Expecter{mock: &_m.Mock}
}

// PollDeviceToken provides a mock function for the type MockLogtoDeviceFlowClient
func (_mock *MockLogtoDeviceFlowClient) PollDeviceToken(ctx context.Context, deviceCode string) (*logto.DeviceTokenResponse, error) {
	ret := _mock.Called(ctx, deviceCode)

	if len(ret) == 0 {
		panic("no return value specified for PollDeviceToken")
	}

	var r0 *logto.DeviceTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*logto.DeviceTokenResponse, error)); ok {
		return returnFunc(ctx, deviceCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *logto.DeviceTokenResponse); ok {
		r0 = returnFunc(ctx, deviceCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*logto.DeviceTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, deviceCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogtoDeviceFlowClient_PollDeviceToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollDeviceToken'
type MockLogtoDeviceFlowClient_PollDeviceToken_Call struct {
	*mock.Call
}

// PollDeviceToken is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceCode string
func (_e *MockLogtoDeviceFlowClient_Expecter) PollDeviceToken(ctx any, deviceCode any) *MockLogtoDeviceFlowClient_PollDeviceToken_Call {
	return &MockLogtoDeviceFlowClient_PollDeviceToken_Call{Call: _e.mock.On("PollDeviceToken", ctx, deviceCode)}
}

func (_c *MockLogtoDeviceFlowClient_PollDeviceToken_Call) Run(run func(ctx context.Context, deviceCode string)) *MockLogtoDeviceFlowClient_PollDeviceToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogtoDeviceFlowClient_PollDeviceToken_Call) Return(deviceTokenResponse *logto.DeviceTokenResponse, err error) *MockLogtoDeviceFlowClient_PollDeviceToken_Call {
	_c.Call.Return(deviceTokenResponse, err)
	return _c
}

func (_c *MockLogtoDeviceFlowClient_PollDeviceToken_Call) RunAndReturn(run func(ctx context.Context, deviceCode string) (*logto.DeviceTokenResponse, error)) *MockLogtoDeviceFlowClient_PollDeviceToken_Call {
	_c.Call.Return(run)
	return _c
}

// RequestDeviceCode provides a mock function for the type MockLogtoDeviceFlowClient
func (_mock *MockLogtoDeviceFlowClient) RequestDeviceCode(ctx context.Context) (*logto.DeviceCodeResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeviceCode")
	}

	var r0 *logto.DeviceCodeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*logto.DeviceCodeResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *logto.DeviceCodeResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*logto.DeviceCodeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogtoDeviceFlowClient_RequestDeviceCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDeviceCode'
type MockLogtoDeviceFlowClient_RequestDeviceCode_Call struct {
	*mock.Call
}

// RequestDeviceCode is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLogtoDeviceFlowClient_Expecter) RequestDeviceCode(ctx any) *MockLogtoDeviceFlowClient_RequestDeviceCode_Call {
	return &MockLogtoDeviceFlowClient_RequestDeviceCode_Call{Call: _e.mock.On("RequestDeviceCode", ctx)}
}

func (_c *MockLogtoDeviceFlowClient_RequestDeviceCode_Call) Run(run func(ctx context.Context)) *MockLogtoDeviceFlowClient_RequestDeviceCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogtoDeviceFlowClient_RequestDeviceCode_Call) Return(deviceCodeResponse *logto.DeviceCodeResponse, err error) *MockLogtoDeviceFlowClient_RequestDeviceCode_Call {
	_c.Call.Return(deviceCodeResponse, err)
	return _c
}

func (_c *MockLogtoDeviceFlowClient_RequestDeviceCode_Call) RunAndReturn(run func(ctx context.Context) (*logto.DeviceCodeResponse, error)) *MockLogtoDeviceFlowClient_RequestDeviceCode_Call {
	_c.Call.Return(run)
	return _c
}
