// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/gofrs/uuid/v5"
	"github.com/muriiloandrade/finsplitter/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateCardBrandRepository creates a new instance of MockCreateCardBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCardBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCardBrandRepository {
	mock := &MockCreateCardBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateCardBrandRepository is an autogenerated mock type for the CreateCardBrandRepository type
type MockCreateCardBrandRepository struct {
	mock.Mock
}

type MockCreateCardBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateCardBrandRepository) EXPECT() *MockCreateCardBrandRepository_Expecter {
	return &MockCreateCardBrandRepository_Expecter{mock: &_m.Mock}
}

// CreateCardBrand provides a mock function for the type MockCreateCardBrandRepository
func (_mock *MockCreateCardBrandRepository) CreateCardBrand(ctx context.Context, name string) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateCardBrandRepository_CreateCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCardBrand'
type MockCreateCardBrandRepository_CreateCardBrand_Call struct {
	*mock.Call
}

// CreateCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCreateCardBrandRepository_Expecter) CreateCardBrand(ctx any, name any) *MockCreateCardBrandRepository_CreateCardBrand_Call {
	return &MockCreateCardBrandRepository_CreateCardBrand_Call{Call: _e.mock.On("CreateCardBrand", ctx, name)}
}

func (_c *MockCreateCardBrandRepository_CreateCardBrand_Call) Run(run func(ctx context.Context, name string)) *MockCreateCardBrandRepository_CreateCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateCardBrandRepository_CreateCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockCreateCardBrandRepository_CreateCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockCreateCardBrandRepository_CreateCardBrand_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.CardBrand, error)) *MockCreateCardBrandRepository_CreateCardBrand_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCardBrandByIDRepository creates a new instance of MockGetCardBrandByIDRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCardBrandByIDRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCardBrandByIDRepository {
	mock := &MockGetCardBrandByIDRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetCardBrandByIDRepository is an autogenerated mock type for the GetCardBrandByIDRepository type
type MockGetCardBrandByIDRepository struct {
	mock.Mock
}

type MockGetCardBrandByIDRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCardBrandByIDRepository) EXPECT() *MockGetCardBrandByIDRepository_Expecter {
	return &MockGetCardBrandByIDRepository_Expecter{mock: &_m.Mock}
}

// GetCardBrandByID provides a mock function for the type MockGetCardBrandByIDRepository
func (_mock *MockGetCardBrandByIDRepository) GetCardBrandByID(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCardBrandByID")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetCardBrandByIDRepository_GetCardBrandByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardBrandByID'
type MockGetCardBrandByIDRepository_GetCardBrandByID_Call struct {
	*mock.Call
}

// GetCardBrandByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGetCardBrandByIDRepository_Expecter) GetCardBrandByID(ctx any, id any) *MockGetCardBrandByIDRepository_GetCardBrandByID_Call {
	return &MockGetCardBrandByIDRepository_GetCardBrandByID_Call{Call: _e.mock.On("GetCardBrandByID", ctx, id)}
}

func (_c *MockGetCardBrandByIDRepository_GetCardBrandByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGetCardBrandByIDRepository_GetCardBrandByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetCardBrandByIDRepository_GetCardBrandByID_Call) Return(cardBrand *entity.CardBrand, err error) *MockGetCardBrandByIDRepository_GetCardBrandByID_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockGetCardBrandByIDRepository_GetCardBrandByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error)) *MockGetCardBrandByIDRepository_GetCardBrandByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListCardBrandRepository creates a new instance of MockListCardBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListCardBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListCardBrandRepository {
	mock := &MockListCardBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListCardBrandRepository is an autogenerated mock type for the ListCardBrandRepository type
type MockListCardBrandRepository struct {
	mock.Mock
}

type MockListCardBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListCardBrandRepository) EXPECT() *MockListCardBrandRepository_Expecter {
	return &MockListCardBrandRepository_Expecter{mock: &_m.Mock}
}

// ListCardBrands provides a mock function for the type MockListCardBrandRepository
func (_mock *MockListCardBrandRepository) ListCardBrands(ctx context.Context, filter ListCardBrandFilterOptions) ([]entity.CardBrand, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListCardBrands")
	}

	var r0 []entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListCardBrandFilterOptions) ([]entity.CardBrand, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListCardBrandFilterOptions) []entity.CardBrand); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ListCardBrandFilterOptions) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListCardBrandRepository_ListCardBrands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCardBrands'
type MockListCardBrandRepository_ListCardBrands_Call struct {
	*mock.Call
}

// ListCardBrands is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ListCardBrandFilterOptions
func (_e *MockListCardBrandRepository_Expecter) ListCardBrands(ctx any, filter any) *MockListCardBrandRepository_ListCardBrands_Call {
	return &MockListCardBrandRepository_ListCardBrands_Call{Call: _e.mock.On("ListCardBrands", ctx, filter)}
}

func (_c *MockListCardBrandRepository_ListCardBrands_Call) Run(run func(ctx context.Context, filter ListCardBrandFilterOptions)) *MockListCardBrandRepository_ListCardBrands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ListCardBrandFilterOptions
		if args[1] != nil {
			arg1 = args[1].(ListCardBrandFilterOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListCardBrandRepository_ListCardBrands_Call) Return(cardBrands []entity.CardBrand, err error) *MockListCardBrandRepository_ListCardBrands_Call {
	_c.Call.Return(cardBrands, err)
	return _c
}

func (_c *MockListCardBrandRepository_ListCardBrands_Call) RunAndReturn(run func(ctx context.Context, filter ListCardBrandFilterOptions) ([]entity.CardBrand, error)) *MockListCardBrandRepository_ListCardBrands_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateCardBrandRepository creates a new instance of MockUpdateCardBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateCardBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateCardBrandRepository {
	mock := &MockUpdateCardBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateCardBrandRepository is an autogenerated mock type for the UpdateCardBrandRepository type
type MockUpdateCardBrandRepository struct {
	mock.Mock
}

type MockUpdateCardBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateCardBrandRepository) EXPECT() *MockUpdateCardBrandRepository_Expecter {
	return &MockUpdateCardBrandRepository_Expecter{mock: &_m.Mock}
}

// UpdateCardBrand provides a mock function for the type MockUpdateCardBrandRepository
func (_mock *MockUpdateCardBrandRepository) UpdateCardBrand(ctx context.Context, opts UpdateCardBrandOptions) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateCardBrandOptions) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateCardBrandOptions) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, UpdateCardBrandOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateCardBrandRepository_UpdateCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCardBrand'
type MockUpdateCardBrandRepository_UpdateCardBrand_Call struct {
	*mock.Call
}

// UpdateCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - opts UpdateCardBrandOptions
func (_e *MockUpdateCardBrandRepository_Expecter) UpdateCardBrand(ctx any, opts any) *MockUpdateCardBrandRepository_UpdateCardBrand_Call {
	return &MockUpdateCardBrandRepository_UpdateCardBrand_Call{Call: _e.mock.On("UpdateCardBrand", ctx, opts)}
}

func (_c *MockUpdateCardBrandRepository_UpdateCardBrand_Call) Run(run func(ctx context.Context, opts UpdateCardBrandOptions)) *MockUpdateCardBrandRepository_UpdateCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpdateCardBrandOptions
		if args[1] != nil {
			arg1 = args[1].(UpdateCardBrandOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateCardBrandRepository_UpdateCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockUpdateCardBrandRepository_UpdateCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockUpdateCardBrandRepository_UpdateCardBrand_Call) RunAndReturn(run func(ctx context.Context, opts UpdateCardBrandOptions) (*entity.CardBrand, error)) *MockUpdateCardBrandRepository_UpdateCardBrand_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteCardBrandRepository creates a new instance of MockDeleteCardBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteCardBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteCardBrandRepository {
	mock := &MockDeleteCardBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleteCardBrandRepository is an autogenerated mock type for the DeleteCardBrandRepository type
type MockDeleteCardBrandRepository struct {
	mock.Mock
}

type MockDeleteCardBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteCardBrandRepository) EXPECT() *MockDeleteCardBrandRepository_Expecter {
	return &MockDeleteCardBrandRepository_Expecter{mock: &_m.Mock}
}

// DeleteCardBrand provides a mock function for the type MockDeleteCardBrandRepository
func (_mock *MockDeleteCardBrandRepository) DeleteCardBrand(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeleteCardBrandRepository_DeleteCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCardBrand'
type MockDeleteCardBrandRepository_DeleteCardBrand_Call struct {
	*mock.Call
}

// DeleteCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeleteCardBrandRepository_Expecter) DeleteCardBrand(ctx any, id any) *MockDeleteCardBrandRepository_DeleteCardBrand_Call {
	return &MockDeleteCardBrandRepository_DeleteCardBrand_Call{Call: _e.mock.On("DeleteCardBrand", ctx, id)}
}

func (_c *MockDeleteCardBrandRepository_DeleteCardBrand_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeleteCardBrandRepository_DeleteCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleteCardBrandRepository_DeleteCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockDeleteCardBrandRepository_DeleteCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockDeleteCardBrandRepository_DeleteCardBrand_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error)) *MockDeleteCardBrandRepository_DeleteCardBrand_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, user *entity.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepository_Expecter) Create(ctx any, user any) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(err error) *MockUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByLogtoUserID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ExistsByLogtoUserID(ctx context.Context, logtoUserID string) (bool, error) {
	ret := _mock.Called(ctx, logtoUserID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByLogtoUserID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, logtoUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, logtoUserID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, logtoUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_ExistsByLogtoUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByLogtoUserID'
type MockUserRepository_ExistsByLogtoUserID_Call struct {
	*mock.Call
}

// ExistsByLogtoUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - logtoUserID string
func (_e *MockUserRepository_Expecter) ExistsByLogtoUserID(ctx any, logtoUserID any) *MockUserRepository_ExistsByLogtoUserID_Call {
	return &MockUserRepository_ExistsByLogtoUserID_Call{Call: _e.mock.On("ExistsByLogtoUserID", ctx, logtoUserID)}
}

func (_c *MockUserRepository_ExistsByLogtoUserID_Call) Run(run func(ctx context.Context, logtoUserID string)) *MockUserRepository_ExistsByLogtoUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_ExistsByLogtoUserID_Call) Return(b bool, err error) *MockUserRepository_ExistsByLogtoUserID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_ExistsByLogtoUserID_Call) RunAndReturn(run func(ctx context.Context, logtoUserID string) (bool, error)) *MockUserRepository_ExistsByLogtoUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) GetByID(ctx any, id any) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(user *entity.User, err error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogtoUserID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByLogtoUserID(ctx context.Context, logtoUserID string) (*entity.User, error) {
	ret := _mock.Called(ctx, logtoUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogtoUserID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, logtoUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, logtoUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, logtoUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByLogtoUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogtoUserID'
type MockUserRepository_GetByLogtoUserID_Call struct {
	*mock.Call
}

// GetByLogtoUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - logtoUserID string
func (_e *MockUserRepository_Expecter) GetByLogtoUserID(ctx any, logtoUserID any) *MockUserRepository_GetByLogtoUserID_Call {
	return &MockUserRepository_GetByLogtoUserID_Call{Call: _e.mock.On("GetByLogtoUserID", ctx, logtoUserID)}
}

func (_c *MockUserRepository_GetByLogtoUserID_Call) Run(run func(ctx context.Context, logtoUserID string)) *MockUserRepository_GetByLogtoUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByLogtoUserID_Call) Return(user *entity.User, err error) *MockUserRepository_GetByLogtoUserID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByLogtoUserID_Call) RunAndReturn(run func(ctx context.Context, logtoUserID string) (*entity.User, error)) *MockUserRepository_GetByLogtoUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateUsername(ctx context.Context, id uuid.UUID, username string) error {
	ret := _mock.Called(ctx, id, username)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUsername")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUsername'
type MockUserRepository_UpdateUsername_Call struct {
	*mock.Call
}

// UpdateUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - username string
func (_e *MockUserRepository_Expecter) UpdateUsername(ctx any, id any, username any) *MockUserRepository_UpdateUsername_Call {
	return &MockUserRepository_UpdateUsername_Call{Call: _e.mock.On("UpdateUsername", ctx, id, username)}
}

func (_c *MockUserRepository_UpdateUsername_Call) Run(run func(ctx context.Context, id uuid.UUID, username string)) *MockUserRepository_UpdateUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateUsername_Call) Return(err error) *MockUserRepository_UpdateUsername_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateUsername_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, username string) error) *MockUserRepository_UpdateUsername_Call {
	_c.Call.Return(run)
	return _c
}
