// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/gofrs/uuid/v5"
	"github.com/muriiloandrade/finsplitter/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateCardBrandRepository creates a new instance of MockCreateCardBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCardBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCardBrandRepository {
	mock := &MockCreateCardBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateCardBrandRepository is an autogenerated mock type for the CreateCardBrandRepository type
type MockCreateCardBrandRepository struct {
	mock.Mock
}

type MockCreateCardBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateCardBrandRepository) EXPECT() *MockCreateCardBrandRepository_Expecter {
	return &MockCreateCardBrandRepository_Expecter{mock: &_m.Mock}
}

// CreateCardBrand provides a mock function for the type MockCreateCardBrandRepository
func (_mock *MockCreateCardBrandRepository) CreateCardBrand(ctx context.Context, name string) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateCardBrandRepository_CreateCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCardBrand'
type MockCreateCardBrandRepository_CreateCardBrand_Call struct {
	*mock.Call
}

// CreateCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCreateCardBrandRepository_Expecter) CreateCardBrand(ctx interface{}, name interface{}) *MockCreateCardBrandRepository_CreateCardBrand_Call {
	return &MockCreateCardBrandRepository_CreateCardBrand_Call{Call: _e.mock.On("CreateCardBrand", ctx, name)}
}

func (_c *MockCreateCardBrandRepository_CreateCardBrand_Call) Run(run func(ctx context.Context, name string)) *MockCreateCardBrandRepository_CreateCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateCardBrandRepository_CreateCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockCreateCardBrandRepository_CreateCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockCreateCardBrandRepository_CreateCardBrand_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.CardBrand, error)) *MockCreateCardBrandRepository_CreateCardBrand_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCardBrandByIdRepository creates a new instance of MockGetCardBrandByIdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCardBrandByIdRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCardBrandByIdRepository {
	mock := &MockGetCardBrandByIdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetCardBrandByIdRepository is an autogenerated mock type for the GetCardBrandByIdRepository type
type MockGetCardBrandByIdRepository struct {
	mock.Mock
}

type MockGetCardBrandByIdRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCardBrandByIdRepository) EXPECT() *MockGetCardBrandByIdRepository_Expecter {
	return &MockGetCardBrandByIdRepository_Expecter{mock: &_m.Mock}
}

// GetCardBrandByID provides a mock function for the type MockGetCardBrandByIdRepository
func (_mock *MockGetCardBrandByIdRepository) GetCardBrandByID(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCardBrandByID")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetCardBrandByIdRepository_GetCardBrandByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardBrandByID'
type MockGetCardBrandByIdRepository_GetCardBrandByID_Call struct {
	*mock.Call
}

// GetCardBrandByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGetCardBrandByIdRepository_Expecter) GetCardBrandByID(ctx interface{}, id interface{}) *MockGetCardBrandByIdRepository_GetCardBrandByID_Call {
	return &MockGetCardBrandByIdRepository_GetCardBrandByID_Call{Call: _e.mock.On("GetCardBrandByID", ctx, id)}
}

func (_c *MockGetCardBrandByIdRepository_GetCardBrandByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGetCardBrandByIdRepository_GetCardBrandByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetCardBrandByIdRepository_GetCardBrandByID_Call) Return(cardBrand *entity.CardBrand, err error) *MockGetCardBrandByIdRepository_GetCardBrandByID_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockGetCardBrandByIdRepository_GetCardBrandByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error)) *MockGetCardBrandByIdRepository_GetCardBrandByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListCardBrandRepository creates a new instance of MockListCardBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListCardBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListCardBrandRepository {
	mock := &MockListCardBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListCardBrandRepository is an autogenerated mock type for the ListCardBrandRepository type
type MockListCardBrandRepository struct {
	mock.Mock
}

type MockListCardBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListCardBrandRepository) EXPECT() *MockListCardBrandRepository_Expecter {
	return &MockListCardBrandRepository_Expecter{mock: &_m.Mock}
}

// ListCardBrands provides a mock function for the type MockListCardBrandRepository
func (_mock *MockListCardBrandRepository) ListCardBrands(ctx context.Context, filter ListCardBrandFilterOptions) ([]entity.CardBrand, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListCardBrands")
	}

	var r0 []entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListCardBrandFilterOptions) ([]entity.CardBrand, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListCardBrandFilterOptions) []entity.CardBrand); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ListCardBrandFilterOptions) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListCardBrandRepository_ListCardBrands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCardBrands'
type MockListCardBrandRepository_ListCardBrands_Call struct {
	*mock.Call
}

// ListCardBrands is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ListCardBrandFilterOptions
func (_e *MockListCardBrandRepository_Expecter) ListCardBrands(ctx interface{}, filter interface{}) *MockListCardBrandRepository_ListCardBrands_Call {
	return &MockListCardBrandRepository_ListCardBrands_Call{Call: _e.mock.On("ListCardBrands", ctx, filter)}
}

func (_c *MockListCardBrandRepository_ListCardBrands_Call) Run(run func(ctx context.Context, filter ListCardBrandFilterOptions)) *MockListCardBrandRepository_ListCardBrands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ListCardBrandFilterOptions
		if args[1] != nil {
			arg1 = args[1].(ListCardBrandFilterOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListCardBrandRepository_ListCardBrands_Call) Return(cardBrands []entity.CardBrand, err error) *MockListCardBrandRepository_ListCardBrands_Call {
	_c.Call.Return(cardBrands, err)
	return _c
}

func (_c *MockListCardBrandRepository_ListCardBrands_Call) RunAndReturn(run func(ctx context.Context, filter ListCardBrandFilterOptions) ([]entity.CardBrand, error)) *MockListCardBrandRepository_ListCardBrands_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateCardBrandRepository creates a new instance of MockUpdateCardBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateCardBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateCardBrandRepository {
	mock := &MockUpdateCardBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateCardBrandRepository is an autogenerated mock type for the UpdateCardBrandRepository type
type MockUpdateCardBrandRepository struct {
	mock.Mock
}

type MockUpdateCardBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateCardBrandRepository) EXPECT() *MockUpdateCardBrandRepository_Expecter {
	return &MockUpdateCardBrandRepository_Expecter{mock: &_m.Mock}
}

// UpdateCardBrand provides a mock function for the type MockUpdateCardBrandRepository
func (_mock *MockUpdateCardBrandRepository) UpdateCardBrand(ctx context.Context, opts UpdateCardBrandOptions) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateCardBrandOptions) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateCardBrandOptions) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, UpdateCardBrandOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateCardBrandRepository_UpdateCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCardBrand'
type MockUpdateCardBrandRepository_UpdateCardBrand_Call struct {
	*mock.Call
}

// UpdateCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - opts UpdateCardBrandOptions
func (_e *MockUpdateCardBrandRepository_Expecter) UpdateCardBrand(ctx interface{}, opts interface{}) *MockUpdateCardBrandRepository_UpdateCardBrand_Call {
	return &MockUpdateCardBrandRepository_UpdateCardBrand_Call{Call: _e.mock.On("UpdateCardBrand", ctx, opts)}
}

func (_c *MockUpdateCardBrandRepository_UpdateCardBrand_Call) Run(run func(ctx context.Context, opts UpdateCardBrandOptions)) *MockUpdateCardBrandRepository_UpdateCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpdateCardBrandOptions
		if args[1] != nil {
			arg1 = args[1].(UpdateCardBrandOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateCardBrandRepository_UpdateCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockUpdateCardBrandRepository_UpdateCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockUpdateCardBrandRepository_UpdateCardBrand_Call) RunAndReturn(run func(ctx context.Context, opts UpdateCardBrandOptions) (*entity.CardBrand, error)) *MockUpdateCardBrandRepository_UpdateCardBrand_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteCardBrandRepository creates a new instance of MockDeleteCardBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteCardBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteCardBrandRepository {
	mock := &MockDeleteCardBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleteCardBrandRepository is an autogenerated mock type for the DeleteCardBrandRepository type
type MockDeleteCardBrandRepository struct {
	mock.Mock
}

type MockDeleteCardBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteCardBrandRepository) EXPECT() *MockDeleteCardBrandRepository_Expecter {
	return &MockDeleteCardBrandRepository_Expecter{mock: &_m.Mock}
}

// DeleteCardBrand provides a mock function for the type MockDeleteCardBrandRepository
func (_mock *MockDeleteCardBrandRepository) DeleteCardBrand(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCardBrand")
	}

	var r0 *entity.CardBrand
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CardBrand, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CardBrand); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CardBrand)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeleteCardBrandRepository_DeleteCardBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCardBrand'
type MockDeleteCardBrandRepository_DeleteCardBrand_Call struct {
	*mock.Call
}

// DeleteCardBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeleteCardBrandRepository_Expecter) DeleteCardBrand(ctx interface{}, id interface{}) *MockDeleteCardBrandRepository_DeleteCardBrand_Call {
	return &MockDeleteCardBrandRepository_DeleteCardBrand_Call{Call: _e.mock.On("DeleteCardBrand", ctx, id)}
}

func (_c *MockDeleteCardBrandRepository_DeleteCardBrand_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeleteCardBrandRepository_DeleteCardBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleteCardBrandRepository_DeleteCardBrand_Call) Return(cardBrand *entity.CardBrand, err error) *MockDeleteCardBrandRepository_DeleteCardBrand_Call {
	_c.Call.Return(cardBrand, err)
	return _c
}

func (_c *MockDeleteCardBrandRepository_DeleteCardBrand_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.CardBrand, error)) *MockDeleteCardBrandRepository_DeleteCardBrand_Call {
	_c.Call.Return(run)
	return _c
}
