// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactioner creates a new instance of MockTransactioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactioner {
	mock := &MockTransactioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactioner is an autogenerated mock type for the Transactioner type
type MockTransactioner struct {
	mock.Mock
}

type MockTransactioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactioner) EXPECT() *MockTransactioner_Expecter {
	return &MockTransactioner_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockTransactioner
func (_mock *MockTransactioner) WithTx(context1 context.Context, transactionFunc TransactionFunc) error {
	ret := _mock.Called(context1, transactionFunc)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TransactionFunc) error); ok {
		r0 = returnFunc(context1, transactionFunc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactioner_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockTransactioner_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - context1 context.Context
//   - transactionFunc TransactionFunc
func (_e *MockTransactioner_Expecter) WithTx(context1 interface{}, transactionFunc interface{}) *MockTransactioner_WithTx_Call {
	return &MockTransactioner_WithTx_Call{Call: _e.mock.On("WithTx", context1, transactionFunc)}
}

func (_c *MockTransactioner_WithTx_Call) Run(run func(context1 context.Context, transactionFunc TransactionFunc)) *MockTransactioner_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TransactionFunc
		if args[1] != nil {
			arg1 = args[1].(TransactionFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactioner_WithTx_Call) Return(err error) *MockTransactioner_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactioner_WithTx_Call) RunAndReturn(run func(context1 context.Context, transactionFunc TransactionFunc) error) *MockTransactioner_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
