name: PR Labeler

on:
    workflow_call:

permissions:
    contents: read
    pull-requests: write

jobs:
    auto_label_pr:
        name: Auto Label PR
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter/autolabeler@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
