name: PR Labeler

on:
    workflow_call:

permissions:
    contents: read
    pull-requests: write

jobs:
    auto_label_pr:
        name: Auto Label PR
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter/autolabeler@c2e2804cc59f45f57076a99af580d0fedb697927 # v7.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
