name: Release Drafter

on:
    workflow_call:
        inputs:
            labeler-only:
                description: "Run in labeler-only mode (disable release notes generation)"
                required: false
                default: false
                type: boolean

permissions:
    contents: write
    pull-requests: write

jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@6db134d15f3909ccc9eefd369f02bd1e9cffdf97 # v6.2.0
              with:
                  config-name: release-drafter.yml
                  disable-releaser: ${{ inputs.labeler-only }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
