name: Security Scan

on:
    workflow_call:
        inputs:
            go-versions:
                description: "Go versions to scan with (JSON array)"
                required: false
                default: '["1.25.4"]'
                type: string
            gosec-args:
                description: "Arguments for Gosec"
                required: false
                default: "-no-fail -fmt sarif -out gosec-results.sarif ./..."
                type: string

jobs:
    analyze:
        name: Analyze (${{ matrix.language }})
        runs-on: "ubuntu-latest"
        permissions:
            security-events: write
            packages: read
            actions: read
            contents: read

        strategy:
            fail-fast: false
            matrix:
                go-version: ${{ fromJSON(inputs.go-versions) }}
                include:
                    - language: actions
                      build-mode: none
                    - language: go
                      build-mode: autobuild
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Set up Go
              uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
              with:
                  go-version: ${{ matrix.go-version }}
                  cache: true

            - name: Run Gosec Security Scanner
              uses: securego/gosec@bb17e422fc34bf4c0a2e5cab9d07dc45a68c040c # v2.24.7
              with:
                  args: ${{ inputs.gosec-args }}

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@c793b717bc78562f491db7b0e93a3a178b099162 # v4
              with:
                  sarif_file: gosec-results.sarif

            - name: Initialize CodeQL
              uses: github/codeql-action/init@c793b717bc78562f491db7b0e93a3a178b099162 # v4
              with:
                  languages: ${{ matrix.language }}
                  build-mode: ${{ matrix.build-mode }}
                  queries: security-and-quality

            # If the analyze step fails for one of the languages you are analyzing with
            # "We were unable to automatically build your code", modify the matrix above
            # to set the build mode to "manual" for that language. Then modify this step
            # to build your code.
            # ℹ️ Command-line programs to run using the OS shell.
            # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
            - name: Run manual build steps
              if: matrix.build-mode == 'manual'
              shell: bash
              run: |
                  echo 'If you are using a "manual" build mode for one or more of the' \
                      'languages you are analyzing, replace this with the commands to build' \
                      'your code, for example:'
                  echo '  make bootstrap'
                  echo '  make release'
                  exit 1

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@c793b717bc78562f491db7b0e93a3a178b099162 # v4
              with:
                  category: "/language:${{matrix.language}}"
